//! Module provides all TDlib types.
//! For types details you can see [TDlib API Scheme](https://github.com/tdlib/td/blob/master/td/generate/scheme/td_api.tl)
pub(crate) use self::_common::{RFunction};
pub use self::_common::{RObject};

#[macro_use]
mod _common;

pub use self::accent_color::*;
pub use self::accept_call::*;
pub use self::accept_terms_of_service::*;
pub use self::account_ttl::*;
pub use self::activate_story_stealth_mode::*;
pub use self::add_application_changelog::*;
pub use self::add_chat_folder_by_invite_link::*;
pub use self::add_chat_member::*;
pub use self::add_chat_members::*;
pub use self::add_chat_to_list::*;
pub use self::add_contact::*;
pub use self::add_custom_server_language_pack::*;
pub use self::add_favorite_sticker::*;
pub use self::add_file_to_downloads::*;
pub use self::add_local_message::*;
pub use self::add_log_message::*;
pub use self::add_message_reaction::*;
pub use self::add_network_statistics::*;
pub use self::add_proxy::*;
pub use self::add_recent_sticker::*;
pub use self::add_recently_found_chat::*;
pub use self::add_saved_animation::*;
pub use self::add_saved_notification_sound::*;
pub use self::add_sticker_to_set::*;
pub use self::added_reaction::*;
pub use self::added_reactions::*;
pub use self::address::*;
pub use self::allow_bot_to_send_messages::*;
pub use self::animated_chat_photo::*;
pub use self::animated_emoji::*;
pub use self::animation::*;
pub use self::animations::*;
pub use self::answer_callback_query::*;
pub use self::answer_custom_query::*;
pub use self::answer_inline_query::*;
pub use self::answer_pre_checkout_query::*;
pub use self::answer_shipping_query::*;
pub use self::answer_web_app_query::*;
pub use self::apply_premium_gift_code::*;
pub use self::archive_chat_list_settings::*;
pub use self::assign_app_store_transaction::*;
pub use self::assign_google_play_transaction::*;
pub use self::attachment_menu_bot::*;
pub use self::attachment_menu_bot_color::*;
pub use self::audio::*;
pub use self::authentication_code_info::*;
pub use self::authentication_code_type::*;
pub use self::authorization_state::*;
pub use self::auto_download_settings::*;
pub use self::auto_download_settings_presets::*;
pub use self::autosave_settings::*;
pub use self::autosave_settings_exception::*;
pub use self::autosave_settings_scope::*;
pub use self::available_reaction::*;
pub use self::available_reactions::*;
pub use self::background::*;
pub use self::background_fill::*;
pub use self::background_type::*;
pub use self::backgrounds::*;
pub use self::ban_chat_member::*;
pub use self::bank_card_action_open_url::*;
pub use self::bank_card_info::*;
pub use self::basic_group::*;
pub use self::basic_group_full_info::*;
pub use self::block_list::*;
pub use self::block_message_sender_from_replies::*;
pub use self::boost_chat::*;
pub use self::bot_command::*;
pub use self::bot_command_scope::*;
pub use self::bot_commands::*;
pub use self::bot_info::*;
pub use self::bot_menu_button::*;
pub use self::bot_write_access_allow_reason::*;
pub use self::call::*;
pub use self::call_discard_reason::*;
pub use self::call_id::*;
pub use self::call_problem::*;
pub use self::call_protocol::*;
pub use self::call_server::*;
pub use self::call_server_type::*;
pub use self::call_state::*;
pub use self::callback_query_answer::*;
pub use self::callback_query_payload::*;
pub use self::can_bot_send_messages::*;
pub use self::can_purchase_premium::*;
pub use self::can_send_story::*;
pub use self::can_send_story_result::*;
pub use self::can_transfer_ownership::*;
pub use self::can_transfer_ownership_result::*;
pub use self::cancel_download_file::*;
pub use self::cancel_password_reset::*;
pub use self::cancel_preliminary_upload_file::*;
pub use self::change_imported_contacts::*;
pub use self::change_phone_number::*;
pub use self::change_sticker_set::*;
pub use self::chat::*;
pub use self::chat_action::*;
pub use self::chat_action_bar::*;
pub use self::chat_active_stories::*;
pub use self::chat_administrator::*;
pub use self::chat_administrator_rights::*;
pub use self::chat_administrators::*;
pub use self::chat_available_reactions::*;
pub use self::chat_background::*;
pub use self::chat_boost::*;
pub use self::chat_boost_link::*;
pub use self::chat_boost_link_info::*;
pub use self::chat_boost_slot::*;
pub use self::chat_boost_slots::*;
pub use self::chat_boost_source::*;
pub use self::chat_boost_status::*;
pub use self::chat_event::*;
pub use self::chat_event_action::*;
pub use self::chat_event_log_filters::*;
pub use self::chat_events::*;
pub use self::chat_folder::*;
pub use self::chat_folder_icon::*;
pub use self::chat_folder_info::*;
pub use self::chat_folder_invite_link::*;
pub use self::chat_folder_invite_link_info::*;
pub use self::chat_folder_invite_links::*;
pub use self::chat_invite_link::*;
pub use self::chat_invite_link_count::*;
pub use self::chat_invite_link_counts::*;
pub use self::chat_invite_link_info::*;
pub use self::chat_invite_link_member::*;
pub use self::chat_invite_link_members::*;
pub use self::chat_invite_links::*;
pub use self::chat_join_request::*;
pub use self::chat_join_requests::*;
pub use self::chat_join_requests_info::*;
pub use self::chat_list::*;
pub use self::chat_lists::*;
pub use self::chat_location::*;
pub use self::chat_member::*;
pub use self::chat_member_status::*;
pub use self::chat_members::*;
pub use self::chat_members_filter::*;
pub use self::chat_message_sender::*;
pub use self::chat_message_senders::*;
pub use self::chat_nearby::*;
pub use self::chat_notification_settings::*;
pub use self::chat_permissions::*;
pub use self::chat_photo::*;
pub use self::chat_photo_info::*;
pub use self::chat_photo_sticker::*;
pub use self::chat_photo_sticker_type::*;
pub use self::chat_photos::*;
pub use self::chat_position::*;
pub use self::chat_source::*;
pub use self::chat_statistics::*;
pub use self::chat_statistics_administrator_actions_info::*;
pub use self::chat_statistics_inviter_info::*;
pub use self::chat_statistics_message_interaction_info::*;
pub use self::chat_statistics_message_sender_info::*;
pub use self::chat_theme::*;
pub use self::chat_type::*;
pub use self::chats::*;
pub use self::chats_nearby::*;
pub use self::check_authentication_bot_token::*;
pub use self::check_authentication_code::*;
pub use self::check_authentication_email_code::*;
pub use self::check_authentication_password::*;
pub use self::check_authentication_password_recovery_code::*;
pub use self::check_change_phone_number_code::*;
pub use self::check_chat_folder_invite_link::*;
pub use self::check_chat_invite_link::*;
pub use self::check_chat_username::*;
pub use self::check_chat_username_result::*;
pub use self::check_created_public_chats_limit::*;
pub use self::check_email_address_verification_code::*;
pub use self::check_login_email_address_code::*;
pub use self::check_password_recovery_code::*;
pub use self::check_phone_number_confirmation_code::*;
pub use self::check_phone_number_verification_code::*;
pub use self::check_premium_gift_code::*;
pub use self::check_recovery_email_address_code::*;
pub use self::check_sticker_set_name::*;
pub use self::check_sticker_set_name_result::*;
pub use self::clean_file_name::*;
pub use self::clear_all_draft_messages::*;
pub use self::clear_autosave_settings_exceptions::*;
pub use self::clear_imported_contacts::*;
pub use self::clear_recent_emoji_statuses::*;
pub use self::clear_recent_reactions::*;
pub use self::clear_recent_stickers::*;
pub use self::clear_recently_found_chats::*;
pub use self::click_animated_emoji_message::*;
pub use self::click_chat_sponsored_message::*;
pub use self::click_premium_subscription_button::*;
pub use self::close::*;
pub use self::close_chat::*;
pub use self::close_secret_chat::*;
pub use self::close_story::*;
pub use self::close_web_app::*;
pub use self::closed_vector_path::*;
pub use self::confirm_qr_code_authentication::*;
pub use self::confirm_session::*;
pub use self::connected_website::*;
pub use self::connected_websites::*;
pub use self::connection_state::*;
pub use self::contact::*;
pub use self::count::*;
pub use self::countries::*;
pub use self::country_info::*;
pub use self::create_basic_group_chat::*;
pub use self::create_call::*;
pub use self::create_chat_folder::*;
pub use self::create_chat_folder_invite_link::*;
pub use self::create_chat_invite_link::*;
pub use self::create_forum_topic::*;
pub use self::create_invoice_link::*;
pub use self::create_new_basic_group_chat::*;
pub use self::create_new_secret_chat::*;
pub use self::create_new_sticker_set::*;
pub use self::create_new_supergroup_chat::*;
pub use self::create_private_chat::*;
pub use self::create_secret_chat::*;
pub use self::create_supergroup_chat::*;
pub use self::create_temporary_password::*;
pub use self::create_video_chat::*;
pub use self::custom_request_result::*;
pub use self::database_statistics::*;
pub use self::date::*;
pub use self::date_range::*;
pub use self::dated_file::*;
pub use self::deep_link_info::*;
pub use self::delete_account::*;
pub use self::delete_all_call_messages::*;
pub use self::delete_all_revoked_chat_invite_links::*;
pub use self::delete_chat::*;
pub use self::delete_chat_folder::*;
pub use self::delete_chat_folder_invite_link::*;
pub use self::delete_chat_history::*;
pub use self::delete_chat_messages_by_date::*;
pub use self::delete_chat_messages_by_sender::*;
pub use self::delete_chat_reply_markup::*;
pub use self::delete_commands::*;
pub use self::delete_file::*;
pub use self::delete_forum_topic::*;
pub use self::delete_language_pack::*;
pub use self::delete_messages::*;
pub use self::delete_passport_element::*;
pub use self::delete_profile_photo::*;
pub use self::delete_revoked_chat_invite_link::*;
pub use self::delete_saved_credentials::*;
pub use self::delete_saved_order_info::*;
pub use self::delete_sticker_set::*;
pub use self::delete_story::*;
pub use self::destroy::*;
pub use self::device_token::*;
pub use self::dice_stickers::*;
pub use self::disable_all_supergroup_usernames::*;
pub use self::disable_proxy::*;
pub use self::discard_call::*;
pub use self::disconnect_all_websites::*;
pub use self::disconnect_website::*;
pub use self::document::*;
pub use self::download_file::*;
pub use self::downloaded_file_counts::*;
pub use self::draft_message::*;
pub use self::edit_chat_folder::*;
pub use self::edit_chat_folder_invite_link::*;
pub use self::edit_chat_invite_link::*;
pub use self::edit_custom_language_pack_info::*;
pub use self::edit_forum_topic::*;
pub use self::edit_inline_message_caption::*;
pub use self::edit_inline_message_live_location::*;
pub use self::edit_inline_message_media::*;
pub use self::edit_inline_message_reply_markup::*;
pub use self::edit_inline_message_text::*;
pub use self::edit_message_caption::*;
pub use self::edit_message_live_location::*;
pub use self::edit_message_media::*;
pub use self::edit_message_reply_markup::*;
pub use self::edit_message_scheduling_state::*;
pub use self::edit_message_text::*;
pub use self::edit_proxy::*;
pub use self::edit_story::*;
pub use self::email_address_authentication::*;
pub use self::email_address_authentication_code_info::*;
pub use self::email_address_reset_state::*;
pub use self::emoji_categories::*;
pub use self::emoji_category::*;
pub use self::emoji_category_type::*;
pub use self::emoji_reaction::*;
pub use self::emoji_status::*;
pub use self::emoji_statuses::*;
pub use self::emojis::*;
pub use self::enable_proxy::*;
pub use self::encrypted_credentials::*;
pub use self::encrypted_passport_element::*;
pub use self::end_group_call::*;
pub use self::end_group_call_recording::*;
pub use self::end_group_call_screen_sharing::*;
pub use self::error::*;
pub use self::file::*;
pub use self::file_download::*;
pub use self::file_downloaded_prefix_size::*;
pub use self::file_part::*;
pub use self::file_type::*;
pub use self::finish_file_generation::*;
pub use self::firebase_authentication_settings::*;
pub use self::formatted_text::*;
pub use self::forum_topic::*;
pub use self::forum_topic_icon::*;
pub use self::forum_topic_info::*;
pub use self::forum_topics::*;
pub use self::forward_messages::*;
pub use self::found_chat_boosts::*;
pub use self::found_chat_messages::*;
pub use self::found_file_downloads::*;
pub use self::found_messages::*;
pub use self::found_position::*;
pub use self::found_positions::*;
pub use self::found_web_app::*;
pub use self::game::*;
pub use self::game_high_score::*;
pub use self::game_high_scores::*;
pub use self::get_account_ttl::*;
pub use self::get_active_live_location_messages::*;
pub use self::get_active_sessions::*;
pub use self::get_all_passport_elements::*;
pub use self::get_all_sticker_emojis::*;
pub use self::get_animated_emoji::*;
pub use self::get_application_config::*;
pub use self::get_application_download_link::*;
pub use self::get_archive_chat_list_settings::*;
pub use self::get_archived_sticker_sets::*;
pub use self::get_attached_sticker_sets::*;
pub use self::get_attachment_menu_bot::*;
pub use self::get_authorization_state::*;
pub use self::get_auto_download_settings_presets::*;
pub use self::get_autosave_settings::*;
pub use self::get_available_chat_boost_slots::*;
pub use self::get_background_url::*;
pub use self::get_backgrounds::*;
pub use self::get_bank_card_info::*;
pub use self::get_basic_group::*;
pub use self::get_basic_group_full_info::*;
pub use self::get_blocked_message_senders::*;
pub use self::get_bot_info_description::*;
pub use self::get_bot_info_short_description::*;
pub use self::get_bot_name::*;
pub use self::get_callback_query_answer::*;
pub use self::get_callback_query_message::*;
pub use self::get_chat::*;
pub use self::get_chat_active_stories::*;
pub use self::get_chat_administrators::*;
pub use self::get_chat_archived_stories::*;
pub use self::get_chat_available_message_senders::*;
pub use self::get_chat_boost_link::*;
pub use self::get_chat_boost_link_info::*;
pub use self::get_chat_boost_status::*;
pub use self::get_chat_boosts::*;
pub use self::get_chat_event_log::*;
pub use self::get_chat_folder::*;
pub use self::get_chat_folder_chat_count::*;
pub use self::get_chat_folder_chats_to_leave::*;
pub use self::get_chat_folder_default_icon_name::*;
pub use self::get_chat_folder_invite_links::*;
pub use self::get_chat_folder_new_chats::*;
pub use self::get_chat_history::*;
pub use self::get_chat_invite_link::*;
pub use self::get_chat_invite_link_counts::*;
pub use self::get_chat_invite_link_members::*;
pub use self::get_chat_invite_links::*;
pub use self::get_chat_join_requests::*;
pub use self::get_chat_lists_to_add_chat::*;
pub use self::get_chat_member::*;
pub use self::get_chat_message_by_date::*;
pub use self::get_chat_message_calendar::*;
pub use self::get_chat_message_count::*;
pub use self::get_chat_message_position::*;
pub use self::get_chat_notification_settings_exceptions::*;
pub use self::get_chat_pinned_message::*;
pub use self::get_chat_pinned_stories::*;
pub use self::get_chat_scheduled_messages::*;
pub use self::get_chat_sparse_message_positions::*;
pub use self::get_chat_sponsored_messages::*;
pub use self::get_chat_statistics::*;
pub use self::get_chats::*;
pub use self::get_chats_for_chat_folder_invite_link::*;
pub use self::get_chats_to_send_stories::*;
pub use self::get_close_friends::*;
pub use self::get_commands::*;
pub use self::get_connected_websites::*;
pub use self::get_contacts::*;
pub use self::get_countries::*;
pub use self::get_country_code::*;
pub use self::get_created_public_chats::*;
pub use self::get_current_state::*;
pub use self::get_custom_emoji_reaction_animations::*;
pub use self::get_custom_emoji_stickers::*;
pub use self::get_database_statistics::*;
pub use self::get_deep_link_info::*;
pub use self::get_default_background_custom_emoji_stickers::*;
pub use self::get_default_chat_photo_custom_emoji_stickers::*;
pub use self::get_default_emoji_statuses::*;
pub use self::get_default_message_auto_delete_time::*;
pub use self::get_default_profile_photo_custom_emoji_stickers::*;
pub use self::get_emoji_categories::*;
pub use self::get_emoji_reaction::*;
pub use self::get_emoji_suggestions_url::*;
pub use self::get_external_link::*;
pub use self::get_external_link_info::*;
pub use self::get_favorite_stickers::*;
pub use self::get_file::*;
pub use self::get_file_downloaded_prefix_size::*;
pub use self::get_file_extension::*;
pub use self::get_file_mime_type::*;
pub use self::get_forum_topic::*;
pub use self::get_forum_topic_default_icons::*;
pub use self::get_forum_topic_link::*;
pub use self::get_forum_topics::*;
pub use self::get_game_high_scores::*;
pub use self::get_group_call::*;
pub use self::get_group_call_invite_link::*;
pub use self::get_group_call_stream_segment::*;
pub use self::get_group_call_streams::*;
pub use self::get_groups_in_common::*;
pub use self::get_imported_contact_count::*;
pub use self::get_inactive_supergroup_chats::*;
pub use self::get_inline_game_high_scores::*;
pub use self::get_inline_query_results::*;
pub use self::get_installed_sticker_sets::*;
pub use self::get_internal_link::*;
pub use self::get_internal_link_type::*;
pub use self::get_json_string::*;
pub use self::get_json_value::*;
pub use self::get_language_pack_info::*;
pub use self::get_language_pack_string::*;
pub use self::get_language_pack_strings::*;
pub use self::get_localization_target_info::*;
pub use self::get_log_stream::*;
pub use self::get_log_tag_verbosity_level::*;
pub use self::get_log_tags::*;
pub use self::get_log_verbosity_level::*;
pub use self::get_login_url::*;
pub use self::get_login_url_info::*;
pub use self::get_map_thumbnail_file::*;
pub use self::get_markdown_text::*;
pub use self::get_me::*;
pub use self::get_menu_button::*;
pub use self::get_message::*;
pub use self::get_message_added_reactions::*;
pub use self::get_message_available_reactions::*;
pub use self::get_message_embedding_code::*;
pub use self::get_message_file_type::*;
pub use self::get_message_import_confirmation_text::*;
pub use self::get_message_link::*;
pub use self::get_message_link_info::*;
pub use self::get_message_locally::*;
pub use self::get_message_public_forwards::*;
pub use self::get_message_statistics::*;
pub use self::get_message_thread::*;
pub use self::get_message_thread_history::*;
pub use self::get_message_viewers::*;
pub use self::get_messages::*;
pub use self::get_network_statistics::*;
pub use self::get_option::*;
pub use self::get_passport_authorization_form::*;
pub use self::get_passport_authorization_form_available_elements::*;
pub use self::get_passport_element::*;
pub use self::get_password_state::*;
pub use self::get_payment_form::*;
pub use self::get_payment_receipt::*;
pub use self::get_phone_number_info::*;
pub use self::get_phone_number_info_sync::*;
pub use self::get_poll_voters::*;
pub use self::get_preferred_country_language::*;
pub use self::get_premium_features::*;
pub use self::get_premium_gift_code_payment_options::*;
pub use self::get_premium_giveaway_info::*;
pub use self::get_premium_limit::*;
pub use self::get_premium_state::*;
pub use self::get_premium_sticker_examples::*;
pub use self::get_premium_stickers::*;
pub use self::get_proxies::*;
pub use self::get_proxy_link::*;
pub use self::get_push_receiver_id::*;
pub use self::get_recent_emoji_statuses::*;
pub use self::get_recent_inline_bots::*;
pub use self::get_recent_stickers::*;
pub use self::get_recently_opened_chats::*;
pub use self::get_recently_visited_t_me_urls::*;
pub use self::get_recommended_chat_folders::*;
pub use self::get_recovery_email_address::*;
pub use self::get_remote_file::*;
pub use self::get_replied_message::*;
pub use self::get_saved_animations::*;
pub use self::get_saved_notification_sound::*;
pub use self::get_saved_notification_sounds::*;
pub use self::get_saved_order_info::*;
pub use self::get_scope_notification_settings::*;
pub use self::get_secret_chat::*;
pub use self::get_statistical_graph::*;
pub use self::get_sticker_emojis::*;
pub use self::get_sticker_set::*;
pub use self::get_stickers::*;
pub use self::get_storage_statistics::*;
pub use self::get_storage_statistics_fast::*;
pub use self::get_story::*;
pub use self::get_story_available_reactions::*;
pub use self::get_story_notification_settings_exceptions::*;
pub use self::get_story_viewers::*;
pub use self::get_suggested_file_name::*;
pub use self::get_suggested_sticker_set_name::*;
pub use self::get_suitable_discussion_chats::*;
pub use self::get_supergroup::*;
pub use self::get_supergroup_full_info::*;
pub use self::get_supergroup_members::*;
pub use self::get_support_name::*;
pub use self::get_support_user::*;
pub use self::get_temporary_password_state::*;
pub use self::get_text_entities::*;
pub use self::get_theme_parameters_json_string::*;
pub use self::get_themed_emoji_statuses::*;
pub use self::get_top_chats::*;
pub use self::get_trending_sticker_sets::*;
pub use self::get_user::*;
pub use self::get_user_chat_boosts::*;
pub use self::get_user_full_info::*;
pub use self::get_user_link::*;
pub use self::get_user_privacy_setting_rules::*;
pub use self::get_user_profile_photos::*;
pub use self::get_user_support_info::*;
pub use self::get_video_chat_available_participants::*;
pub use self::get_video_chat_rtmp_url::*;
pub use self::get_web_app_link_url::*;
pub use self::get_web_app_url::*;
pub use self::get_web_page_instant_view::*;
pub use self::get_web_page_preview::*;
pub use self::group_call::*;
pub use self::group_call_id::*;
pub use self::group_call_participant::*;
pub use self::group_call_participant_video_info::*;
pub use self::group_call_recent_speaker::*;
pub use self::group_call_stream::*;
pub use self::group_call_streams::*;
pub use self::group_call_video_quality::*;
pub use self::group_call_video_source_group::*;
pub use self::hashtags::*;
pub use self::hide_suggested_action::*;
pub use self::http_url::*;
pub use self::identity_document::*;
pub use self::import_contacts::*;
pub use self::import_messages::*;
pub use self::imported_contacts::*;
pub use self::inline_keyboard_button::*;
pub use self::inline_keyboard_button_type::*;
pub use self::inline_query_result::*;
pub use self::inline_query_results::*;
pub use self::inline_query_results_button::*;
pub use self::inline_query_results_button_type::*;
pub use self::input_background::*;
pub use self::input_chat_photo::*;
pub use self::input_credentials::*;
pub use self::input_file::*;
pub use self::input_identity_document::*;
pub use self::input_inline_query_result::*;
pub use self::input_invoice::*;
pub use self::input_message_content::*;
pub use self::input_message_reply_to::*;
pub use self::input_passport_element::*;
pub use self::input_passport_element_error::*;
pub use self::input_passport_element_error_source::*;
pub use self::input_personal_document::*;
pub use self::input_sticker::*;
pub use self::input_story_area::*;
pub use self::input_story_area_type::*;
pub use self::input_story_areas::*;
pub use self::input_story_content::*;
pub use self::input_thumbnail::*;
pub use self::internal_link_type::*;
pub use self::invite_group_call_participants::*;
pub use self::invite_link_chat_type::*;
pub use self::invoice::*;
pub use self::join_chat::*;
pub use self::join_chat_by_invite_link::*;
pub use self::join_group_call::*;
pub use self::json_object_member::*;
pub use self::json_value::*;
pub use self::keyboard_button::*;
pub use self::keyboard_button_type::*;
pub use self::labeled_price_part::*;
pub use self::language_pack_info::*;
pub use self::language_pack_string::*;
pub use self::language_pack_string_value::*;
pub use self::language_pack_strings::*;
pub use self::launch_prepaid_premium_giveaway::*;
pub use self::leave_chat::*;
pub use self::leave_group_call::*;
pub use self::link_preview_options::*;
pub use self::load_active_stories::*;
pub use self::load_chats::*;
pub use self::load_group_call_participants::*;
pub use self::local_file::*;
pub use self::localization_target_info::*;
pub use self::location::*;
pub use self::log_out::*;
pub use self::log_stream::*;
pub use self::log_tags::*;
pub use self::log_verbosity_level::*;
pub use self::login_url_info::*;
pub use self::mask_point::*;
pub use self::mask_position::*;
pub use self::message::*;
pub use self::message_auto_delete_time::*;
pub use self::message_calendar::*;
pub use self::message_calendar_day::*;
pub use self::message_content::*;
pub use self::message_copy_options::*;
pub use self::message_extended_media::*;
pub use self::message_file_type::*;
pub use self::message_forward_info::*;
pub use self::message_import_info::*;
pub use self::message_interaction_info::*;
pub use self::message_link::*;
pub use self::message_link_info::*;
pub use self::message_origin::*;
pub use self::message_position::*;
pub use self::message_positions::*;
pub use self::message_reaction::*;
pub use self::message_reply_info::*;
pub use self::message_reply_to::*;
pub use self::message_scheduling_state::*;
pub use self::message_self_destruct_type::*;
pub use self::message_send_options::*;
pub use self::message_sender::*;
pub use self::message_senders::*;
pub use self::message_sending_state::*;
pub use self::message_source::*;
pub use self::message_sponsor::*;
pub use self::message_sponsor_type::*;
pub use self::message_statistics::*;
pub use self::message_thread_info::*;
pub use self::message_viewer::*;
pub use self::message_viewers::*;
pub use self::messages::*;
pub use self::minithumbnail::*;
pub use self::network_statistics::*;
pub use self::network_statistics_entry::*;
pub use self::network_type::*;
pub use self::notification::*;
pub use self::notification_group::*;
pub use self::notification_group_type::*;
pub use self::notification_settings_scope::*;
pub use self::notification_sound::*;
pub use self::notification_sounds::*;
pub use self::notification_type::*;
pub use self::ok::*;
pub use self::open_chat::*;
pub use self::open_message_content::*;
pub use self::open_story::*;
pub use self::open_web_app::*;
pub use self::optimize_storage::*;
pub use self::option_value::*;
pub use self::order_info::*;
pub use self::page_block::*;
pub use self::page_block_caption::*;
pub use self::page_block_horizontal_alignment::*;
pub use self::page_block_list_item::*;
pub use self::page_block_related_article::*;
pub use self::page_block_table_cell::*;
pub use self::page_block_vertical_alignment::*;
pub use self::parse_markdown::*;
pub use self::parse_text_entities::*;
pub use self::passport_authorization_form::*;
pub use self::passport_element::*;
pub use self::passport_element_error::*;
pub use self::passport_element_error_source::*;
pub use self::passport_element_type::*;
pub use self::passport_elements::*;
pub use self::passport_elements_with_errors::*;
pub use self::passport_required_element::*;
pub use self::passport_suitable_element::*;
pub use self::password_state::*;
pub use self::payment_form::*;
pub use self::payment_option::*;
pub use self::payment_provider::*;
pub use self::payment_receipt::*;
pub use self::payment_result::*;
pub use self::personal_details::*;
pub use self::personal_document::*;
pub use self::phone_number_authentication_settings::*;
pub use self::phone_number_info::*;
pub use self::photo::*;
pub use self::photo_size::*;
pub use self::pin_chat_message::*;
pub use self::ping_proxy::*;
pub use self::point::*;
pub use self::poll::*;
pub use self::poll_option::*;
pub use self::poll_type::*;
pub use self::preliminary_upload_file::*;
pub use self::premium_feature::*;
pub use self::premium_feature_promotion_animation::*;
pub use self::premium_features::*;
pub use self::premium_gift_code_info::*;
pub use self::premium_gift_code_payment_option::*;
pub use self::premium_gift_code_payment_options::*;
pub use self::premium_giveaway_info::*;
pub use self::premium_giveaway_parameters::*;
pub use self::premium_giveaway_participant_status::*;
pub use self::premium_limit::*;
pub use self::premium_limit_type::*;
pub use self::premium_payment_option::*;
pub use self::premium_source::*;
pub use self::premium_state::*;
pub use self::premium_state_payment_option::*;
pub use self::premium_story_feature::*;
pub use self::prepaid_premium_giveaway::*;
pub use self::process_chat_folder_new_chats::*;
pub use self::process_chat_join_request::*;
pub use self::process_chat_join_requests::*;
pub use self::process_push_notification::*;
pub use self::profile_photo::*;
pub use self::proxies::*;
pub use self::proxy::*;
pub use self::proxy_type::*;
pub use self::public_chat_type::*;
pub use self::push_message_content::*;
pub use self::push_receiver_id::*;
pub use self::rate_speech_recognition::*;
pub use self::reaction_type::*;
pub use self::read_all_chat_mentions::*;
pub use self::read_all_chat_reactions::*;
pub use self::read_all_message_thread_mentions::*;
pub use self::read_all_message_thread_reactions::*;
pub use self::read_chat_list::*;
pub use self::read_file_part::*;
pub use self::recognize_speech::*;
pub use self::recommended_chat_folder::*;
pub use self::recommended_chat_folders::*;
pub use self::recover_authentication_password::*;
pub use self::recover_password::*;
pub use self::recovery_email_address::*;
pub use self::register_device::*;
pub use self::register_user::*;
pub use self::remote_file::*;
pub use self::remove_all_files_from_downloads::*;
pub use self::remove_background::*;
pub use self::remove_chat_action_bar::*;
pub use self::remove_contacts::*;
pub use self::remove_favorite_sticker::*;
pub use self::remove_file_from_downloads::*;
pub use self::remove_message_reaction::*;
pub use self::remove_notification::*;
pub use self::remove_notification_group::*;
pub use self::remove_proxy::*;
pub use self::remove_recent_hashtag::*;
pub use self::remove_recent_sticker::*;
pub use self::remove_recently_found_chat::*;
pub use self::remove_saved_animation::*;
pub use self::remove_saved_notification_sound::*;
pub use self::remove_sticker_from_set::*;
pub use self::remove_top_chat::*;
pub use self::reorder_active_usernames::*;
pub use self::reorder_bot_active_usernames::*;
pub use self::reorder_chat_folders::*;
pub use self::reorder_installed_sticker_sets::*;
pub use self::reorder_supergroup_active_usernames::*;
pub use self::replace_primary_chat_invite_link::*;
pub use self::replace_video_chat_rtmp_url::*;
pub use self::reply_markup::*;
pub use self::report_chat::*;
pub use self::report_chat_photo::*;
pub use self::report_message_reactions::*;
pub use self::report_reason::*;
pub use self::report_story::*;
pub use self::report_supergroup_anti_spam_false_positive::*;
pub use self::report_supergroup_spam::*;
pub use self::request_authentication_password_recovery::*;
pub use self::request_password_recovery::*;
pub use self::request_qr_code_authentication::*;
pub use self::resend_authentication_code::*;
pub use self::resend_change_phone_number_code::*;
pub use self::resend_email_address_verification_code::*;
pub use self::resend_login_email_address_code::*;
pub use self::resend_messages::*;
pub use self::resend_phone_number_confirmation_code::*;
pub use self::resend_phone_number_verification_code::*;
pub use self::resend_recovery_email_address_code::*;
pub use self::reset_all_notification_settings::*;
pub use self::reset_authentication_email_address::*;
pub use self::reset_backgrounds::*;
pub use self::reset_network_statistics::*;
pub use self::reset_password::*;
pub use self::reset_password_result::*;
pub use self::revoke_chat_invite_link::*;
pub use self::revoke_group_call_invite_link::*;
pub use self::rich_text::*;
pub use self::rtmp_url::*;
pub use self::save_application_log_event::*;
pub use self::saved_credentials::*;
pub use self::scope_autosave_settings::*;
pub use self::scope_notification_settings::*;
pub use self::search_background::*;
pub use self::search_call_messages::*;
pub use self::search_chat_members::*;
pub use self::search_chat_messages::*;
pub use self::search_chat_recent_location_messages::*;
pub use self::search_chats::*;
pub use self::search_chats_nearby::*;
pub use self::search_chats_on_server::*;
pub use self::search_contacts::*;
pub use self::search_emojis::*;
pub use self::search_file_downloads::*;
pub use self::search_hashtags::*;
pub use self::search_installed_sticker_sets::*;
pub use self::search_messages::*;
pub use self::search_messages_filter::*;
pub use self::search_outgoing_document_messages::*;
pub use self::search_public_chat::*;
pub use self::search_public_chats::*;
pub use self::search_quote::*;
pub use self::search_recently_found_chats::*;
pub use self::search_secret_messages::*;
pub use self::search_sticker_set::*;
pub use self::search_sticker_sets::*;
pub use self::search_stickers::*;
pub use self::search_strings_by_prefix::*;
pub use self::search_user_by_phone_number::*;
pub use self::search_user_by_token::*;
pub use self::search_web_app::*;
pub use self::seconds::*;
pub use self::secret_chat::*;
pub use self::secret_chat_state::*;
pub use self::send_authentication_firebase_sms::*;
pub use self::send_bot_start_message::*;
pub use self::send_call_debug_information::*;
pub use self::send_call_log::*;
pub use self::send_call_rating::*;
pub use self::send_call_signaling_data::*;
pub use self::send_chat_action::*;
pub use self::send_custom_request::*;
pub use self::send_email_address_verification_code::*;
pub use self::send_inline_query_result_message::*;
pub use self::send_message::*;
pub use self::send_message_album::*;
pub use self::send_passport_authorization_form::*;
pub use self::send_payment_form::*;
pub use self::send_phone_number_confirmation_code::*;
pub use self::send_phone_number_verification_code::*;
pub use self::send_story::*;
pub use self::send_web_app_custom_request::*;
pub use self::send_web_app_data::*;
pub use self::sent_web_app_message::*;
pub use self::session::*;
pub use self::session_type::*;
pub use self::sessions::*;
pub use self::set_accent_color::*;
pub use self::set_account_ttl::*;
pub use self::set_alarm::*;
pub use self::set_archive_chat_list_settings::*;
pub use self::set_authentication_email_address::*;
pub use self::set_authentication_phone_number::*;
pub use self::set_auto_download_settings::*;
pub use self::set_autosave_settings::*;
pub use self::set_background::*;
pub use self::set_bio::*;
pub use self::set_bot_info_description::*;
pub use self::set_bot_info_short_description::*;
pub use self::set_bot_name::*;
pub use self::set_bot_profile_photo::*;
pub use self::set_bot_updates_status::*;
pub use self::set_chat_accent_color::*;
pub use self::set_chat_active_stories_list::*;
pub use self::set_chat_available_reactions::*;
pub use self::set_chat_background::*;
pub use self::set_chat_client_data::*;
pub use self::set_chat_description::*;
pub use self::set_chat_discussion_group::*;
pub use self::set_chat_draft_message::*;
pub use self::set_chat_location::*;
pub use self::set_chat_member_status::*;
pub use self::set_chat_message_auto_delete_time::*;
pub use self::set_chat_message_sender::*;
pub use self::set_chat_notification_settings::*;
pub use self::set_chat_permissions::*;
pub use self::set_chat_photo::*;
pub use self::set_chat_slow_mode_delay::*;
pub use self::set_chat_theme::*;
pub use self::set_chat_title::*;
pub use self::set_close_friends::*;
pub use self::set_commands::*;
pub use self::set_custom_emoji_sticker_set_thumbnail::*;
pub use self::set_custom_language_pack::*;
pub use self::set_custom_language_pack_string::*;
pub use self::set_database_encryption_key::*;
pub use self::set_default_channel_administrator_rights::*;
pub use self::set_default_group_administrator_rights::*;
pub use self::set_default_message_auto_delete_time::*;
pub use self::set_default_reaction_type::*;
pub use self::set_emoji_status::*;
pub use self::set_file_generation_progress::*;
pub use self::set_forum_topic_notification_settings::*;
pub use self::set_game_score::*;
pub use self::set_group_call_participant_is_speaking::*;
pub use self::set_group_call_participant_volume_level::*;
pub use self::set_group_call_title::*;
pub use self::set_inactive_session_ttl::*;
pub use self::set_inline_game_score::*;
pub use self::set_location::*;
pub use self::set_log_stream::*;
pub use self::set_log_tag_verbosity_level::*;
pub use self::set_log_verbosity_level::*;
pub use self::set_login_email_address::*;
pub use self::set_menu_button::*;
pub use self::set_message_sender_block_list::*;
pub use self::set_name::*;
pub use self::set_network_type::*;
pub use self::set_option::*;
pub use self::set_passport_element::*;
pub use self::set_passport_element_errors::*;
pub use self::set_password::*;
pub use self::set_pinned_chats::*;
pub use self::set_pinned_forum_topics::*;
pub use self::set_poll_answer::*;
pub use self::set_profile_photo::*;
pub use self::set_recovery_email_address::*;
pub use self::set_scope_notification_settings::*;
pub use self::set_sticker_emojis::*;
pub use self::set_sticker_keywords::*;
pub use self::set_sticker_mask_position::*;
pub use self::set_sticker_position_in_set::*;
pub use self::set_sticker_set_thumbnail::*;
pub use self::set_sticker_set_title::*;
pub use self::set_story_privacy_settings::*;
pub use self::set_story_reaction::*;
pub use self::set_supergroup_sticker_set::*;
pub use self::set_supergroup_username::*;
pub use self::set_tdlib_parameters::*;
pub use self::set_user_personal_profile_photo::*;
pub use self::set_user_privacy_setting_rules::*;
pub use self::set_user_support_info::*;
pub use self::set_username::*;
pub use self::set_video_chat_default_participant::*;
pub use self::share_chat_with_bot::*;
pub use self::share_phone_number::*;
pub use self::share_user_with_bot::*;
pub use self::shipping_option::*;
pub use self::speech_recognition_result::*;
pub use self::sponsored_message::*;
pub use self::sponsored_messages::*;
pub use self::start_group_call_recording::*;
pub use self::start_group_call_screen_sharing::*;
pub use self::start_scheduled_group_call::*;
pub use self::statistical_graph::*;
pub use self::statistical_value::*;
pub use self::sticker::*;
pub use self::sticker_format::*;
pub use self::sticker_full_type::*;
pub use self::sticker_set::*;
pub use self::sticker_set_info::*;
pub use self::sticker_sets::*;
pub use self::sticker_type::*;
pub use self::stickers::*;
pub use self::stop_poll::*;
pub use self::storage_statistics::*;
pub use self::storage_statistics_by_chat::*;
pub use self::storage_statistics_by_file_type::*;
pub use self::storage_statistics_fast::*;
pub use self::store_payment_purpose::*;
pub use self::stories::*;
pub use self::story::*;
pub use self::story_area::*;
pub use self::story_area_position::*;
pub use self::story_area_type::*;
pub use self::story_content::*;
pub use self::story_info::*;
pub use self::story_interaction_info::*;
pub use self::story_list::*;
pub use self::story_privacy_settings::*;
pub use self::story_video::*;
pub use self::story_viewer::*;
pub use self::story_viewers::*;
pub use self::suggest_user_profile_photo::*;
pub use self::suggested_action::*;
pub use self::supergroup::*;
pub use self::supergroup_full_info::*;
pub use self::supergroup_members_filter::*;
pub use self::synchronize_language_pack::*;
pub use self::t_me_url::*;
pub use self::t_me_url_type::*;
pub use self::t_me_urls::*;
pub use self::target_chat::*;
pub use self::telegram_payment_purpose::*;
pub use self::temporary_password_state::*;
pub use self::terminate_all_other_sessions::*;
pub use self::terminate_session::*;
pub use self::terms_of_service::*;
pub use self::test_bytes::*;
pub use self::test_call_bytes::*;
pub use self::test_call_empty::*;
pub use self::test_call_string::*;
pub use self::test_call_vector_int::*;
pub use self::test_call_vector_int_object::*;
pub use self::test_call_vector_string::*;
pub use self::test_call_vector_string_object::*;
pub use self::test_get_difference::*;
pub use self::test_int::*;
pub use self::test_network::*;
pub use self::test_proxy::*;
pub use self::test_return_error::*;
pub use self::test_square_int::*;
pub use self::test_string::*;
pub use self::test_use_update::*;
pub use self::test_vector_int::*;
pub use self::test_vector_int_object::*;
pub use self::test_vector_string::*;
pub use self::test_vector_string_object::*;
pub use self::text::*;
pub use self::text_entities::*;
pub use self::text_entity::*;
pub use self::text_entity_type::*;
pub use self::text_parse_mode::*;
pub use self::theme_parameters::*;
pub use self::theme_settings::*;
pub use self::thumbnail::*;
pub use self::thumbnail_format::*;
pub use self::toggle_all_downloads_are_paused::*;
pub use self::toggle_bot_is_added_to_attachment_menu::*;
pub use self::toggle_bot_username_is_active::*;
pub use self::toggle_chat_default_disable_notification::*;
pub use self::toggle_chat_has_protected_content::*;
pub use self::toggle_chat_is_marked_as_unread::*;
pub use self::toggle_chat_is_pinned::*;
pub use self::toggle_chat_is_translatable::*;
pub use self::toggle_download_is_paused::*;
pub use self::toggle_forum_topic_is_closed::*;
pub use self::toggle_forum_topic_is_pinned::*;
pub use self::toggle_general_forum_topic_is_hidden::*;
pub use self::toggle_group_call_enabled_start_notification::*;
pub use self::toggle_group_call_is_my_video_enabled::*;
pub use self::toggle_group_call_is_my_video_paused::*;
pub use self::toggle_group_call_mute_new_participants::*;
pub use self::toggle_group_call_participant_is_hand_raised::*;
pub use self::toggle_group_call_participant_is_muted::*;
pub use self::toggle_group_call_screen_sharing_is_paused::*;
pub use self::toggle_session_can_accept_calls::*;
pub use self::toggle_session_can_accept_secret_chats::*;
pub use self::toggle_story_is_pinned::*;
pub use self::toggle_supergroup_has_aggressive_anti_spam_enabled::*;
pub use self::toggle_supergroup_has_hidden_members::*;
pub use self::toggle_supergroup_is_all_history_available::*;
pub use self::toggle_supergroup_is_broadcast_group::*;
pub use self::toggle_supergroup_is_forum::*;
pub use self::toggle_supergroup_join_by_request::*;
pub use self::toggle_supergroup_join_to_send_messages::*;
pub use self::toggle_supergroup_sign_messages::*;
pub use self::toggle_supergroup_username_is_active::*;
pub use self::toggle_username_is_active::*;
pub use self::top_chat_category::*;
pub use self::transfer_chat_ownership::*;
pub use self::translate_message_text::*;
pub use self::translate_text::*;
pub use self::trending_sticker_sets::*;
pub use self::unconfirmed_session::*;
pub use self::unpin_all_chat_messages::*;
pub use self::unpin_all_message_thread_messages::*;
pub use self::unpin_chat_message::*;
pub use self::unread_reaction::*;
pub use self::update::*;
pub use self::updates::*;
pub use self::upgrade_basic_group_chat_to_supergroup_chat::*;
pub use self::upload_sticker_file::*;
pub use self::user::*;
pub use self::user_full_info::*;
pub use self::user_link::*;
pub use self::user_privacy_setting::*;
pub use self::user_privacy_setting_rule::*;
pub use self::user_privacy_setting_rules::*;
pub use self::user_status::*;
pub use self::user_support_info::*;
pub use self::user_type::*;
pub use self::usernames::*;
pub use self::users::*;
pub use self::validate_order_info::*;
pub use self::validated_order_info::*;
pub use self::vector_path_command::*;
pub use self::venue::*;
pub use self::video::*;
pub use self::video_chat::*;
pub use self::video_note::*;
pub use self::view_messages::*;
pub use self::view_premium_feature::*;
pub use self::view_trending_sticker_sets::*;
pub use self::voice_note::*;
pub use self::web_app::*;
pub use self::web_app_info::*;
pub use self::web_page::*;
pub use self::web_page_instant_view::*;
pub use self::write_generated_file_part::*;

mod accent_color;
mod accept_call;
mod accept_terms_of_service;
mod account_ttl;
mod activate_story_stealth_mode;
mod add_application_changelog;
mod add_chat_folder_by_invite_link;
mod add_chat_member;
mod add_chat_members;
mod add_chat_to_list;
mod add_contact;
mod add_custom_server_language_pack;
mod add_favorite_sticker;
mod add_file_to_downloads;
mod add_local_message;
mod add_log_message;
mod add_message_reaction;
mod add_network_statistics;
mod add_proxy;
mod add_recent_sticker;
mod add_recently_found_chat;
mod add_saved_animation;
mod add_saved_notification_sound;
mod add_sticker_to_set;
mod added_reaction;
mod added_reactions;
mod address;
mod allow_bot_to_send_messages;
mod animated_chat_photo;
mod animated_emoji;
mod animation;
mod animations;
mod answer_callback_query;
mod answer_custom_query;
mod answer_inline_query;
mod answer_pre_checkout_query;
mod answer_shipping_query;
mod answer_web_app_query;
mod apply_premium_gift_code;
mod archive_chat_list_settings;
mod assign_app_store_transaction;
mod assign_google_play_transaction;
mod attachment_menu_bot;
mod attachment_menu_bot_color;
mod audio;
mod authentication_code_info;
mod authentication_code_type;
mod authorization_state;
mod auto_download_settings;
mod auto_download_settings_presets;
mod autosave_settings;
mod autosave_settings_exception;
mod autosave_settings_scope;
mod available_reaction;
mod available_reactions;
mod background;
mod background_fill;
mod background_type;
mod backgrounds;
mod ban_chat_member;
mod bank_card_action_open_url;
mod bank_card_info;
mod basic_group;
mod basic_group_full_info;
mod block_list;
mod block_message_sender_from_replies;
mod boost_chat;
mod bot_command;
mod bot_command_scope;
mod bot_commands;
mod bot_info;
mod bot_menu_button;
mod bot_write_access_allow_reason;
mod call;
mod call_discard_reason;
mod call_id;
mod call_problem;
mod call_protocol;
mod call_server;
mod call_server_type;
mod call_state;
mod callback_query_answer;
mod callback_query_payload;
mod can_bot_send_messages;
mod can_purchase_premium;
mod can_send_story;
mod can_send_story_result;
mod can_transfer_ownership;
mod can_transfer_ownership_result;
mod cancel_download_file;
mod cancel_password_reset;
mod cancel_preliminary_upload_file;
mod change_imported_contacts;
mod change_phone_number;
mod change_sticker_set;
mod chat;
mod chat_action;
mod chat_action_bar;
mod chat_active_stories;
mod chat_administrator;
mod chat_administrator_rights;
mod chat_administrators;
mod chat_available_reactions;
mod chat_background;
mod chat_boost;
mod chat_boost_link;
mod chat_boost_link_info;
mod chat_boost_slot;
mod chat_boost_slots;
mod chat_boost_source;
mod chat_boost_status;
mod chat_event;
mod chat_event_action;
mod chat_event_log_filters;
mod chat_events;
mod chat_folder;
mod chat_folder_icon;
mod chat_folder_info;
mod chat_folder_invite_link;
mod chat_folder_invite_link_info;
mod chat_folder_invite_links;
mod chat_invite_link;
mod chat_invite_link_count;
mod chat_invite_link_counts;
mod chat_invite_link_info;
mod chat_invite_link_member;
mod chat_invite_link_members;
mod chat_invite_links;
mod chat_join_request;
mod chat_join_requests;
mod chat_join_requests_info;
mod chat_list;
mod chat_lists;
mod chat_location;
mod chat_member;
mod chat_member_status;
mod chat_members;
mod chat_members_filter;
mod chat_message_sender;
mod chat_message_senders;
mod chat_nearby;
mod chat_notification_settings;
mod chat_permissions;
mod chat_photo;
mod chat_photo_info;
mod chat_photo_sticker;
mod chat_photo_sticker_type;
mod chat_photos;
mod chat_position;
mod chat_source;
mod chat_statistics;
mod chat_statistics_administrator_actions_info;
mod chat_statistics_inviter_info;
mod chat_statistics_message_interaction_info;
mod chat_statistics_message_sender_info;
mod chat_theme;
mod chat_type;
mod chats;
mod chats_nearby;
mod check_authentication_bot_token;
mod check_authentication_code;
mod check_authentication_email_code;
mod check_authentication_password;
mod check_authentication_password_recovery_code;
mod check_change_phone_number_code;
mod check_chat_folder_invite_link;
mod check_chat_invite_link;
mod check_chat_username;
mod check_chat_username_result;
mod check_created_public_chats_limit;
mod check_email_address_verification_code;
mod check_login_email_address_code;
mod check_password_recovery_code;
mod check_phone_number_confirmation_code;
mod check_phone_number_verification_code;
mod check_premium_gift_code;
mod check_recovery_email_address_code;
mod check_sticker_set_name;
mod check_sticker_set_name_result;
mod clean_file_name;
mod clear_all_draft_messages;
mod clear_autosave_settings_exceptions;
mod clear_imported_contacts;
mod clear_recent_emoji_statuses;
mod clear_recent_reactions;
mod clear_recent_stickers;
mod clear_recently_found_chats;
mod click_animated_emoji_message;
mod click_chat_sponsored_message;
mod click_premium_subscription_button;
mod close;
mod close_chat;
mod close_secret_chat;
mod close_story;
mod close_web_app;
mod closed_vector_path;
mod confirm_qr_code_authentication;
mod confirm_session;
mod connected_website;
mod connected_websites;
mod connection_state;
mod contact;
mod count;
mod countries;
mod country_info;
mod create_basic_group_chat;
mod create_call;
mod create_chat_folder;
mod create_chat_folder_invite_link;
mod create_chat_invite_link;
mod create_forum_topic;
mod create_invoice_link;
mod create_new_basic_group_chat;
mod create_new_secret_chat;
mod create_new_sticker_set;
mod create_new_supergroup_chat;
mod create_private_chat;
mod create_secret_chat;
mod create_supergroup_chat;
mod create_temporary_password;
mod create_video_chat;
mod custom_request_result;
mod database_statistics;
mod date;
mod date_range;
mod dated_file;
mod deep_link_info;
mod delete_account;
mod delete_all_call_messages;
mod delete_all_revoked_chat_invite_links;
mod delete_chat;
mod delete_chat_folder;
mod delete_chat_folder_invite_link;
mod delete_chat_history;
mod delete_chat_messages_by_date;
mod delete_chat_messages_by_sender;
mod delete_chat_reply_markup;
mod delete_commands;
mod delete_file;
mod delete_forum_topic;
mod delete_language_pack;
mod delete_messages;
mod delete_passport_element;
mod delete_profile_photo;
mod delete_revoked_chat_invite_link;
mod delete_saved_credentials;
mod delete_saved_order_info;
mod delete_sticker_set;
mod delete_story;
mod destroy;
mod device_token;
mod dice_stickers;
mod disable_all_supergroup_usernames;
mod disable_proxy;
mod discard_call;
mod disconnect_all_websites;
mod disconnect_website;
mod document;
mod download_file;
mod downloaded_file_counts;
mod draft_message;
mod edit_chat_folder;
mod edit_chat_folder_invite_link;
mod edit_chat_invite_link;
mod edit_custom_language_pack_info;
mod edit_forum_topic;
mod edit_inline_message_caption;
mod edit_inline_message_live_location;
mod edit_inline_message_media;
mod edit_inline_message_reply_markup;
mod edit_inline_message_text;
mod edit_message_caption;
mod edit_message_live_location;
mod edit_message_media;
mod edit_message_reply_markup;
mod edit_message_scheduling_state;
mod edit_message_text;
mod edit_proxy;
mod edit_story;
mod email_address_authentication;
mod email_address_authentication_code_info;
mod email_address_reset_state;
mod emoji_categories;
mod emoji_category;
mod emoji_category_type;
mod emoji_reaction;
mod emoji_status;
mod emoji_statuses;
mod emojis;
mod enable_proxy;
mod encrypted_credentials;
mod encrypted_passport_element;
mod end_group_call;
mod end_group_call_recording;
mod end_group_call_screen_sharing;
mod error;
mod file;
mod file_download;
mod file_downloaded_prefix_size;
mod file_part;
mod file_type;
mod finish_file_generation;
mod firebase_authentication_settings;
mod formatted_text;
mod forum_topic;
mod forum_topic_icon;
mod forum_topic_info;
mod forum_topics;
mod forward_messages;
mod found_chat_boosts;
mod found_chat_messages;
mod found_file_downloads;
mod found_messages;
mod found_position;
mod found_positions;
mod found_web_app;
mod game;
mod game_high_score;
mod game_high_scores;
mod get_account_ttl;
mod get_active_live_location_messages;
mod get_active_sessions;
mod get_all_passport_elements;
mod get_all_sticker_emojis;
mod get_animated_emoji;
mod get_application_config;
mod get_application_download_link;
mod get_archive_chat_list_settings;
mod get_archived_sticker_sets;
mod get_attached_sticker_sets;
mod get_attachment_menu_bot;
mod get_authorization_state;
mod get_auto_download_settings_presets;
mod get_autosave_settings;
mod get_available_chat_boost_slots;
mod get_background_url;
mod get_backgrounds;
mod get_bank_card_info;
mod get_basic_group;
mod get_basic_group_full_info;
mod get_blocked_message_senders;
mod get_bot_info_description;
mod get_bot_info_short_description;
mod get_bot_name;
mod get_callback_query_answer;
mod get_callback_query_message;
mod get_chat;
mod get_chat_active_stories;
mod get_chat_administrators;
mod get_chat_archived_stories;
mod get_chat_available_message_senders;
mod get_chat_boost_link;
mod get_chat_boost_link_info;
mod get_chat_boost_status;
mod get_chat_boosts;
mod get_chat_event_log;
mod get_chat_folder;
mod get_chat_folder_chat_count;
mod get_chat_folder_chats_to_leave;
mod get_chat_folder_default_icon_name;
mod get_chat_folder_invite_links;
mod get_chat_folder_new_chats;
mod get_chat_history;
mod get_chat_invite_link;
mod get_chat_invite_link_counts;
mod get_chat_invite_link_members;
mod get_chat_invite_links;
mod get_chat_join_requests;
mod get_chat_lists_to_add_chat;
mod get_chat_member;
mod get_chat_message_by_date;
mod get_chat_message_calendar;
mod get_chat_message_count;
mod get_chat_message_position;
mod get_chat_notification_settings_exceptions;
mod get_chat_pinned_message;
mod get_chat_pinned_stories;
mod get_chat_scheduled_messages;
mod get_chat_sparse_message_positions;
mod get_chat_sponsored_messages;
mod get_chat_statistics;
mod get_chats;
mod get_chats_for_chat_folder_invite_link;
mod get_chats_to_send_stories;
mod get_close_friends;
mod get_commands;
mod get_connected_websites;
mod get_contacts;
mod get_countries;
mod get_country_code;
mod get_created_public_chats;
mod get_current_state;
mod get_custom_emoji_reaction_animations;
mod get_custom_emoji_stickers;
mod get_database_statistics;
mod get_deep_link_info;
mod get_default_background_custom_emoji_stickers;
mod get_default_chat_photo_custom_emoji_stickers;
mod get_default_emoji_statuses;
mod get_default_message_auto_delete_time;
mod get_default_profile_photo_custom_emoji_stickers;
mod get_emoji_categories;
mod get_emoji_reaction;
mod get_emoji_suggestions_url;
mod get_external_link;
mod get_external_link_info;
mod get_favorite_stickers;
mod get_file;
mod get_file_downloaded_prefix_size;
mod get_file_extension;
mod get_file_mime_type;
mod get_forum_topic;
mod get_forum_topic_default_icons;
mod get_forum_topic_link;
mod get_forum_topics;
mod get_game_high_scores;
mod get_group_call;
mod get_group_call_invite_link;
mod get_group_call_stream_segment;
mod get_group_call_streams;
mod get_groups_in_common;
mod get_imported_contact_count;
mod get_inactive_supergroup_chats;
mod get_inline_game_high_scores;
mod get_inline_query_results;
mod get_installed_sticker_sets;
mod get_internal_link;
mod get_internal_link_type;
mod get_json_string;
mod get_json_value;
mod get_language_pack_info;
mod get_language_pack_string;
mod get_language_pack_strings;
mod get_localization_target_info;
mod get_log_stream;
mod get_log_tag_verbosity_level;
mod get_log_tags;
mod get_log_verbosity_level;
mod get_login_url;
mod get_login_url_info;
mod get_map_thumbnail_file;
mod get_markdown_text;
mod get_me;
mod get_menu_button;
mod get_message;
mod get_message_added_reactions;
mod get_message_available_reactions;
mod get_message_embedding_code;
mod get_message_file_type;
mod get_message_import_confirmation_text;
mod get_message_link;
mod get_message_link_info;
mod get_message_locally;
mod get_message_public_forwards;
mod get_message_statistics;
mod get_message_thread;
mod get_message_thread_history;
mod get_message_viewers;
mod get_messages;
mod get_network_statistics;
mod get_option;
mod get_passport_authorization_form;
mod get_passport_authorization_form_available_elements;
mod get_passport_element;
mod get_password_state;
mod get_payment_form;
mod get_payment_receipt;
mod get_phone_number_info;
mod get_phone_number_info_sync;
mod get_poll_voters;
mod get_preferred_country_language;
mod get_premium_features;
mod get_premium_gift_code_payment_options;
mod get_premium_giveaway_info;
mod get_premium_limit;
mod get_premium_state;
mod get_premium_sticker_examples;
mod get_premium_stickers;
mod get_proxies;
mod get_proxy_link;
mod get_push_receiver_id;
mod get_recent_emoji_statuses;
mod get_recent_inline_bots;
mod get_recent_stickers;
mod get_recently_opened_chats;
mod get_recently_visited_t_me_urls;
mod get_recommended_chat_folders;
mod get_recovery_email_address;
mod get_remote_file;
mod get_replied_message;
mod get_saved_animations;
mod get_saved_notification_sound;
mod get_saved_notification_sounds;
mod get_saved_order_info;
mod get_scope_notification_settings;
mod get_secret_chat;
mod get_statistical_graph;
mod get_sticker_emojis;
mod get_sticker_set;
mod get_stickers;
mod get_storage_statistics;
mod get_storage_statistics_fast;
mod get_story;
mod get_story_available_reactions;
mod get_story_notification_settings_exceptions;
mod get_story_viewers;
mod get_suggested_file_name;
mod get_suggested_sticker_set_name;
mod get_suitable_discussion_chats;
mod get_supergroup;
mod get_supergroup_full_info;
mod get_supergroup_members;
mod get_support_name;
mod get_support_user;
mod get_temporary_password_state;
mod get_text_entities;
mod get_theme_parameters_json_string;
mod get_themed_emoji_statuses;
mod get_top_chats;
mod get_trending_sticker_sets;
mod get_user;
mod get_user_chat_boosts;
mod get_user_full_info;
mod get_user_link;
mod get_user_privacy_setting_rules;
mod get_user_profile_photos;
mod get_user_support_info;
mod get_video_chat_available_participants;
mod get_video_chat_rtmp_url;
mod get_web_app_link_url;
mod get_web_app_url;
mod get_web_page_instant_view;
mod get_web_page_preview;
mod group_call;
mod group_call_id;
mod group_call_participant;
mod group_call_participant_video_info;
mod group_call_recent_speaker;
mod group_call_stream;
mod group_call_streams;
mod group_call_video_quality;
mod group_call_video_source_group;
mod hashtags;
mod hide_suggested_action;
mod http_url;
mod identity_document;
mod import_contacts;
mod import_messages;
mod imported_contacts;
mod inline_keyboard_button;
mod inline_keyboard_button_type;
mod inline_query_result;
mod inline_query_results;
mod inline_query_results_button;
mod inline_query_results_button_type;
mod input_background;
mod input_chat_photo;
mod input_credentials;
mod input_file;
mod input_identity_document;
mod input_inline_query_result;
mod input_invoice;
mod input_message_content;
mod input_message_reply_to;
mod input_passport_element;
mod input_passport_element_error;
mod input_passport_element_error_source;
mod input_personal_document;
mod input_sticker;
mod input_story_area;
mod input_story_area_type;
mod input_story_areas;
mod input_story_content;
mod input_thumbnail;
mod internal_link_type;
mod invite_group_call_participants;
mod invite_link_chat_type;
mod invoice;
mod join_chat;
mod join_chat_by_invite_link;
mod join_group_call;
mod json_object_member;
mod json_value;
mod keyboard_button;
mod keyboard_button_type;
mod labeled_price_part;
mod language_pack_info;
mod language_pack_string;
mod language_pack_string_value;
mod language_pack_strings;
mod launch_prepaid_premium_giveaway;
mod leave_chat;
mod leave_group_call;
mod link_preview_options;
mod load_active_stories;
mod load_chats;
mod load_group_call_participants;
mod local_file;
mod localization_target_info;
mod location;
mod log_out;
mod log_stream;
mod log_tags;
mod log_verbosity_level;
mod login_url_info;
mod mask_point;
mod mask_position;
mod message;
mod message_auto_delete_time;
mod message_calendar;
mod message_calendar_day;
mod message_content;
mod message_copy_options;
mod message_extended_media;
mod message_file_type;
mod message_forward_info;
mod message_import_info;
mod message_interaction_info;
mod message_link;
mod message_link_info;
mod message_origin;
mod message_position;
mod message_positions;
mod message_reaction;
mod message_reply_info;
mod message_reply_to;
mod message_scheduling_state;
mod message_self_destruct_type;
mod message_send_options;
mod message_sender;
mod message_senders;
mod message_sending_state;
mod message_source;
mod message_sponsor;
mod message_sponsor_type;
mod message_statistics;
mod message_thread_info;
mod message_viewer;
mod message_viewers;
mod messages;
mod minithumbnail;
mod network_statistics;
mod network_statistics_entry;
mod network_type;
mod notification;
mod notification_group;
mod notification_group_type;
mod notification_settings_scope;
mod notification_sound;
mod notification_sounds;
mod notification_type;
mod ok;
mod open_chat;
mod open_message_content;
mod open_story;
mod open_web_app;
mod optimize_storage;
mod option_value;
mod order_info;
mod page_block;
mod page_block_caption;
mod page_block_horizontal_alignment;
mod page_block_list_item;
mod page_block_related_article;
mod page_block_table_cell;
mod page_block_vertical_alignment;
mod parse_markdown;
mod parse_text_entities;
mod passport_authorization_form;
mod passport_element;
mod passport_element_error;
mod passport_element_error_source;
mod passport_element_type;
mod passport_elements;
mod passport_elements_with_errors;
mod passport_required_element;
mod passport_suitable_element;
mod password_state;
mod payment_form;
mod payment_option;
mod payment_provider;
mod payment_receipt;
mod payment_result;
mod personal_details;
mod personal_document;
mod phone_number_authentication_settings;
mod phone_number_info;
mod photo;
mod photo_size;
mod pin_chat_message;
mod ping_proxy;
mod point;
mod poll;
mod poll_option;
mod poll_type;
mod preliminary_upload_file;
mod premium_feature;
mod premium_feature_promotion_animation;
mod premium_features;
mod premium_gift_code_info;
mod premium_gift_code_payment_option;
mod premium_gift_code_payment_options;
mod premium_giveaway_info;
mod premium_giveaway_parameters;
mod premium_giveaway_participant_status;
mod premium_limit;
mod premium_limit_type;
mod premium_payment_option;
mod premium_source;
mod premium_state;
mod premium_state_payment_option;
mod premium_story_feature;
mod prepaid_premium_giveaway;
mod process_chat_folder_new_chats;
mod process_chat_join_request;
mod process_chat_join_requests;
mod process_push_notification;
mod profile_photo;
mod proxies;
mod proxy;
mod proxy_type;
mod public_chat_type;
mod push_message_content;
mod push_receiver_id;
mod rate_speech_recognition;
mod reaction_type;
mod read_all_chat_mentions;
mod read_all_chat_reactions;
mod read_all_message_thread_mentions;
mod read_all_message_thread_reactions;
mod read_chat_list;
mod read_file_part;
mod recognize_speech;
mod recommended_chat_folder;
mod recommended_chat_folders;
mod recover_authentication_password;
mod recover_password;
mod recovery_email_address;
mod register_device;
mod register_user;
mod remote_file;
mod remove_all_files_from_downloads;
mod remove_background;
mod remove_chat_action_bar;
mod remove_contacts;
mod remove_favorite_sticker;
mod remove_file_from_downloads;
mod remove_message_reaction;
mod remove_notification;
mod remove_notification_group;
mod remove_proxy;
mod remove_recent_hashtag;
mod remove_recent_sticker;
mod remove_recently_found_chat;
mod remove_saved_animation;
mod remove_saved_notification_sound;
mod remove_sticker_from_set;
mod remove_top_chat;
mod reorder_active_usernames;
mod reorder_bot_active_usernames;
mod reorder_chat_folders;
mod reorder_installed_sticker_sets;
mod reorder_supergroup_active_usernames;
mod replace_primary_chat_invite_link;
mod replace_video_chat_rtmp_url;
mod reply_markup;
mod report_chat;
mod report_chat_photo;
mod report_message_reactions;
mod report_reason;
mod report_story;
mod report_supergroup_anti_spam_false_positive;
mod report_supergroup_spam;
mod request_authentication_password_recovery;
mod request_password_recovery;
mod request_qr_code_authentication;
mod resend_authentication_code;
mod resend_change_phone_number_code;
mod resend_email_address_verification_code;
mod resend_login_email_address_code;
mod resend_messages;
mod resend_phone_number_confirmation_code;
mod resend_phone_number_verification_code;
mod resend_recovery_email_address_code;
mod reset_all_notification_settings;
mod reset_authentication_email_address;
mod reset_backgrounds;
mod reset_network_statistics;
mod reset_password;
mod reset_password_result;
mod revoke_chat_invite_link;
mod revoke_group_call_invite_link;
mod rich_text;
mod rtmp_url;
mod save_application_log_event;
mod saved_credentials;
mod scope_autosave_settings;
mod scope_notification_settings;
mod search_background;
mod search_call_messages;
mod search_chat_members;
mod search_chat_messages;
mod search_chat_recent_location_messages;
mod search_chats;
mod search_chats_nearby;
mod search_chats_on_server;
mod search_contacts;
mod search_emojis;
mod search_file_downloads;
mod search_hashtags;
mod search_installed_sticker_sets;
mod search_messages;
mod search_messages_filter;
mod search_outgoing_document_messages;
mod search_public_chat;
mod search_public_chats;
mod search_quote;
mod search_recently_found_chats;
mod search_secret_messages;
mod search_sticker_set;
mod search_sticker_sets;
mod search_stickers;
mod search_strings_by_prefix;
mod search_user_by_phone_number;
mod search_user_by_token;
mod search_web_app;
mod seconds;
mod secret_chat;
mod secret_chat_state;
mod send_authentication_firebase_sms;
mod send_bot_start_message;
mod send_call_debug_information;
mod send_call_log;
mod send_call_rating;
mod send_call_signaling_data;
mod send_chat_action;
mod send_custom_request;
mod send_email_address_verification_code;
mod send_inline_query_result_message;
mod send_message;
mod send_message_album;
mod send_passport_authorization_form;
mod send_payment_form;
mod send_phone_number_confirmation_code;
mod send_phone_number_verification_code;
mod send_story;
mod send_web_app_custom_request;
mod send_web_app_data;
mod sent_web_app_message;
mod session;
mod session_type;
mod sessions;
mod set_accent_color;
mod set_account_ttl;
mod set_alarm;
mod set_archive_chat_list_settings;
mod set_authentication_email_address;
mod set_authentication_phone_number;
mod set_auto_download_settings;
mod set_autosave_settings;
mod set_background;
mod set_bio;
mod set_bot_info_description;
mod set_bot_info_short_description;
mod set_bot_name;
mod set_bot_profile_photo;
mod set_bot_updates_status;
mod set_chat_accent_color;
mod set_chat_active_stories_list;
mod set_chat_available_reactions;
mod set_chat_background;
mod set_chat_client_data;
mod set_chat_description;
mod set_chat_discussion_group;
mod set_chat_draft_message;
mod set_chat_location;
mod set_chat_member_status;
mod set_chat_message_auto_delete_time;
mod set_chat_message_sender;
mod set_chat_notification_settings;
mod set_chat_permissions;
mod set_chat_photo;
mod set_chat_slow_mode_delay;
mod set_chat_theme;
mod set_chat_title;
mod set_close_friends;
mod set_commands;
mod set_custom_emoji_sticker_set_thumbnail;
mod set_custom_language_pack;
mod set_custom_language_pack_string;
mod set_database_encryption_key;
mod set_default_channel_administrator_rights;
mod set_default_group_administrator_rights;
mod set_default_message_auto_delete_time;
mod set_default_reaction_type;
mod set_emoji_status;
mod set_file_generation_progress;
mod set_forum_topic_notification_settings;
mod set_game_score;
mod set_group_call_participant_is_speaking;
mod set_group_call_participant_volume_level;
mod set_group_call_title;
mod set_inactive_session_ttl;
mod set_inline_game_score;
mod set_location;
mod set_log_stream;
mod set_log_tag_verbosity_level;
mod set_log_verbosity_level;
mod set_login_email_address;
mod set_menu_button;
mod set_message_sender_block_list;
mod set_name;
mod set_network_type;
mod set_option;
mod set_passport_element;
mod set_passport_element_errors;
mod set_password;
mod set_pinned_chats;
mod set_pinned_forum_topics;
mod set_poll_answer;
mod set_profile_photo;
mod set_recovery_email_address;
mod set_scope_notification_settings;
mod set_sticker_emojis;
mod set_sticker_keywords;
mod set_sticker_mask_position;
mod set_sticker_position_in_set;
mod set_sticker_set_thumbnail;
mod set_sticker_set_title;
mod set_story_privacy_settings;
mod set_story_reaction;
mod set_supergroup_sticker_set;
mod set_supergroup_username;
mod set_tdlib_parameters;
mod set_user_personal_profile_photo;
mod set_user_privacy_setting_rules;
mod set_user_support_info;
mod set_username;
mod set_video_chat_default_participant;
mod share_chat_with_bot;
mod share_phone_number;
mod share_user_with_bot;
mod shipping_option;
mod speech_recognition_result;
mod sponsored_message;
mod sponsored_messages;
mod start_group_call_recording;
mod start_group_call_screen_sharing;
mod start_scheduled_group_call;
mod statistical_graph;
mod statistical_value;
mod sticker;
mod sticker_format;
mod sticker_full_type;
mod sticker_set;
mod sticker_set_info;
mod sticker_sets;
mod sticker_type;
mod stickers;
mod stop_poll;
mod storage_statistics;
mod storage_statistics_by_chat;
mod storage_statistics_by_file_type;
mod storage_statistics_fast;
mod store_payment_purpose;
mod stories;
mod story;
mod story_area;
mod story_area_position;
mod story_area_type;
mod story_content;
mod story_info;
mod story_interaction_info;
mod story_list;
mod story_privacy_settings;
mod story_video;
mod story_viewer;
mod story_viewers;
mod suggest_user_profile_photo;
mod suggested_action;
mod supergroup;
mod supergroup_full_info;
mod supergroup_members_filter;
mod synchronize_language_pack;
mod t_me_url;
mod t_me_url_type;
mod t_me_urls;
mod target_chat;
mod telegram_payment_purpose;
mod temporary_password_state;
mod terminate_all_other_sessions;
mod terminate_session;
mod terms_of_service;
mod test_bytes;
mod test_call_bytes;
mod test_call_empty;
mod test_call_string;
mod test_call_vector_int;
mod test_call_vector_int_object;
mod test_call_vector_string;
mod test_call_vector_string_object;
mod test_get_difference;
mod test_int;
mod test_network;
mod test_proxy;
mod test_return_error;
mod test_square_int;
mod test_string;
mod test_use_update;
mod test_vector_int;
mod test_vector_int_object;
mod test_vector_string;
mod test_vector_string_object;
mod text;
mod text_entities;
mod text_entity;
mod text_entity_type;
mod text_parse_mode;
mod theme_parameters;
mod theme_settings;
mod thumbnail;
mod thumbnail_format;
mod toggle_all_downloads_are_paused;
mod toggle_bot_is_added_to_attachment_menu;
mod toggle_bot_username_is_active;
mod toggle_chat_default_disable_notification;
mod toggle_chat_has_protected_content;
mod toggle_chat_is_marked_as_unread;
mod toggle_chat_is_pinned;
mod toggle_chat_is_translatable;
mod toggle_download_is_paused;
mod toggle_forum_topic_is_closed;
mod toggle_forum_topic_is_pinned;
mod toggle_general_forum_topic_is_hidden;
mod toggle_group_call_enabled_start_notification;
mod toggle_group_call_is_my_video_enabled;
mod toggle_group_call_is_my_video_paused;
mod toggle_group_call_mute_new_participants;
mod toggle_group_call_participant_is_hand_raised;
mod toggle_group_call_participant_is_muted;
mod toggle_group_call_screen_sharing_is_paused;
mod toggle_session_can_accept_calls;
mod toggle_session_can_accept_secret_chats;
mod toggle_story_is_pinned;
mod toggle_supergroup_has_aggressive_anti_spam_enabled;
mod toggle_supergroup_has_hidden_members;
mod toggle_supergroup_is_all_history_available;
mod toggle_supergroup_is_broadcast_group;
mod toggle_supergroup_is_forum;
mod toggle_supergroup_join_by_request;
mod toggle_supergroup_join_to_send_messages;
mod toggle_supergroup_sign_messages;
mod toggle_supergroup_username_is_active;
mod toggle_username_is_active;
mod top_chat_category;
mod transfer_chat_ownership;
mod translate_message_text;
mod translate_text;
mod trending_sticker_sets;
mod unconfirmed_session;
mod unpin_all_chat_messages;
mod unpin_all_message_thread_messages;
mod unpin_chat_message;
mod unread_reaction;
mod update;
mod updates;
mod upgrade_basic_group_chat_to_supergroup_chat;
mod upload_sticker_file;
mod user;
mod user_full_info;
mod user_link;
mod user_privacy_setting;
mod user_privacy_setting_rule;
mod user_privacy_setting_rules;
mod user_status;
mod user_support_info;
mod user_type;
mod usernames;
mod users;
mod validate_order_info;
mod validated_order_info;
mod vector_path_command;
mod venue;
mod video;
mod video_chat;
mod video_note;
mod view_messages;
mod view_premium_feature;
mod view_trending_sticker_sets;
mod voice_note;
mod web_app;
mod web_app_info;
mod web_page;
mod web_page_instant_view;
mod write_generated_file_part;
